include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for opkg-autoupgrade
LUCI_DEPENDS:=+luci-base +opkg-autoupgrade

PKG_VERSION:=0.0.1
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Cameron Thompson <cameronst2@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
